//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karavann.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class oplata
    {
        public int id { get; set; }
        public string nal { get; set; }
        public string beznal { get; set; }
    }
}
