//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karavann.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tovar
    {
        public int id { get; set; }
        public string naimenovanie { get; set; }
        public string kategoria { get; set; }
        public string cena { get; set; }
        public string opisanie { get; set; }
        public string ves { get; set; }
    }
}
